name: 'PR freshness check'
description: 'Check PR freshness'
author: 'Sharon (Sean) Rolel'
inputs:
  hours: # change this
    required: true
    description: 'how many hours behind default branch is considered fresh'
    default: 24
runs:
  using: 'node12'
  main: 'dist/index.js'
