name: 'PR freshness check'
description: 'Check PR freshness'
author: 'Sharon (Sean) Rolel'
inputs:
  GITHUB_TOKEN:
    required: true
    description: 'github token used for making API requests'
  freshnessHours:
    required: true
    description: 'how many hours behind target branch is considered fresh'
    default: 24
runs:
  using: 'node12'
  main: 'dist/index.js'
